//! Lexicon completion for the input method — task `A-038b`, doc 04 §8 (4.1.1).
//!
//! A11's first condition is **≥30 WPM**, and a typist reaching that in
//! Devanagari is not typing every akṣara of `स्तूपसूचकः`. Completion is what
//! makes the number attainable: type the SLP1 the fingers already know, take
//! the ratified word from a list.
//!
//! # It completes to the lexicon, and only to the lexicon
//!
//! Doc 01 §4 rule 5 is *one word, one sense*, and `spec/lexicon.tsv` is where
//! that is decided. An input method that completed to anything else — a
//! frequency list, the file being edited, a model's guess — would be a second
//! vocabulary competing with the ratified one, and the second always wins
//! because it is the one at the fingertips. So the candidate set is exactly the
//! lexicon.
//!
//! # Matching is on SLP1, because that is what is typed
//!
//! The lexicon carries `devanagari`, `slp1`, `iast`, `english`. The typist is
//! producing SLP1 (`A-038a`: every sign is one keystroke there), so the prefix
//! is matched against the `slp1` column and the Devanagari is what comes back.
//! A Devanagari prefix works too — someone pasting or arrow-keying through
//! existing text is still entitled to completion.
//!
//! # Ordering is total, so the first candidate never moves
//!
//! Ranked by length, then by SLP1. There is no frequency data and inventing one
//! would make the first candidate — the one a fast typist takes without
//! looking — depend on a number nobody measured. Shortest-first is a rule a
//! typist can hold in their head, and ties break the same way every run, which
//! is also what makes this testable.

extern crate alloc;

use alloc::vec::Vec;

/// The ratified vocabulary, as generated by `cargo run -p lexgen`.
const LEXICON: &str = include_str!("../../../spec/lexicon.tsv");

/// One ratified word, in the two scripts the input method needs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Term {
    /// The word as written.
    pub devanagari: &'static str,
    /// The word as typed.
    pub slp1: &'static str,
    /// What it means, for a completion list that shows more than shapes.
    pub english: &'static str,
}

/// Every term the lexicon ratifies.
///
/// Parsed on each call rather than held in a static: the table is 481 rows and
/// the caller is a keystroke handler, not a hot loop. Measuring before caching
/// is the rule (`W-017`), and nothing has measured this yet.
#[must_use]
pub fn terms() -> Vec<Term> {
    LEXICON
        .lines()
        .filter(|l| !l.starts_with('#'))
        .filter_map(|l| {
            let mut f = l.split('\t');
            let (Some(devanagari), Some(slp1), Some(_iast), Some(english)) =
                (f.next(), f.next(), f.next(), f.next())
            else {
                return None;
            };
            // The generated file carries its own column header.
            if devanagari == "devanagari" || devanagari.is_empty() {
                return None;
            }
            Some(Term {
                devanagari,
                slp1,
                english,
            })
        })
        .collect()
}

/// Candidates for `prefix`, best first, at most `limit` of them.
///
/// The prefix may be SLP1 or Devanagari; an empty prefix has no candidates,
/// because offering all 481 words to someone who has typed nothing is not
/// completion.
#[must_use]
pub fn candidates(prefix: &str, limit: usize) -> Vec<Term> {
    if prefix.is_empty() || limit == 0 {
        return Vec::new();
    }
    let mut hits: Vec<Term> = terms()
        .into_iter()
        .filter(|t| t.slp1.starts_with(prefix) || t.devanagari.starts_with(prefix))
        .collect();
    // Total order: shortest first, then by what was typed to reach it.
    hits.sort_unstable_by(|a, b| {
        a.slp1
            .chars()
            .count()
            .cmp(&b.slp1.chars().count())
            .then_with(|| a.slp1.cmp(b.slp1))
    });
    hits.truncate(limit);
    hits
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The parse must find the whole lexicon.
    ///
    /// A parser that matches nothing returns no candidates, which reads exactly
    /// like a prefix nobody has a word for. `A-010`'s lexicon is ≥400 terms by
    /// gate A10, so anything far below that means the columns moved.
    #[test]
    fn the_lexicon_actually_parses() {
        let t = terms();
        assert!(
            t.len() >= 400,
            "parsed only {} terms — spec/lexicon.tsv's columns probably moved",
            t.len()
        );
        for term in &t {
            assert!(!term.devanagari.is_empty(), "a term with no word");
            assert!(!term.slp1.is_empty(), "`{}` has no SLP1", term.devanagari);
        }
    }

    /// Every ratified word is reachable by typing it out.
    ///
    /// Derived rather than sampled: if completion cannot offer a word when the
    /// whole word has been typed, it cannot offer it at all, and this exercises
    /// all 481 rather than the handful a hand-written case would.
    #[test]
    fn every_term_completes_from_its_own_spelling() {
        for term in terms() {
            let got = candidates(term.slp1, 64);
            assert!(
                got.iter().any(|c| c.devanagari == term.devanagari),
                "`{}` typed in full offers {} candidates and none of them is itself",
                term.slp1,
                got.len()
            );
        }
    }

    #[test]
    fn a_prefix_offers_the_shortest_word_first() {
        // Whatever the lexicon holds, the ordering rule must hold over it.
        let got = candidates("s", 16);
        assert!(got.len() > 1, "expected several words starting with `s`");
        for pair in got.windows(2) {
            let (a, b) = (&pair[0], &pair[1]);
            assert!(
                a.slp1.chars().count() < b.slp1.chars().count()
                    || (a.slp1.chars().count() == b.slp1.chars().count() && a.slp1 <= b.slp1),
                "`{}` came before `{}`, which is neither shorter nor earlier",
                a.slp1,
                b.slp1
            );
        }
    }

    #[test]
    fn the_same_prefix_gives_the_same_answer_every_time() {
        // A completion list that reorders between keystrokes is worse than none:
        // the typist takes the first candidate without looking.
        assert_eq!(candidates("sa", 8), candidates("sa", 8));
    }

    #[test]
    fn devanagari_prefixes_complete_too() {
        let first = terms()[0];
        let head: alloc::string::String = first.devanagari.chars().take(2).collect();
        let got = candidates(&head, 64);
        assert!(
            got.iter().any(|c| c.devanagari == first.devanagari),
            "`{head}` offers nothing containing `{}`",
            first.devanagari
        );
    }

    #[test]
    fn nothing_is_offered_for_nothing() {
        assert!(candidates("", 8).is_empty());
        assert!(candidates("s", 0).is_empty());
        assert!(
            candidates("qqqqzz", 8).is_empty(),
            "a prefix no word starts with must offer nothing"
        );
    }
}
