//! The SANSOS text kernel.
//!
//! Everything above this crate — the assembler's tokenizer, the terminal's cell
//! model, the shaper, the linker's symbol table — depends on agreeing what a
//! character *is*. See `research/01-sanskrit-computing-foundations.md`.
//!
//! Tables in [`tables`] are generated by `cargo run -p ucdgen` from the pinned
//! UCD; they are checked in so that building SANSOS needs no network.

//! `normalize` needs an allocator; segmentation (task `A-014`) must stay
//! allocation-free so the terminal line discipline can use it (doc 04 §3).
#![no_std]
// Enforced, not asserted. The fuzz targets run without AddressSanitizer,
// because ASan's runtime traps on this host before `main` (see
// `tools/check-fuzz.sh`). That is only acceptable while this crate has no
// `unsafe` in it: safe Rust's memory errors are panics, and libFuzzer catches
// panics unaided. Removing this line removes the fuzzing argument with it.
#![forbid(unsafe_code)]

pub mod completion;
pub mod ident;
pub mod ime;
pub mod length;
pub mod normalize;
pub mod numeral;
pub mod phonology;
pub mod props;
pub mod repertoire;
pub mod sandhi;
pub mod segment;
pub mod slp1;
pub mod tables;
pub mod varga;
pub mod visarga;

pub use ident::{
    IdentError, is_valid as is_valid_identifier, same_symbol, validate as validate_identifier,
};
pub use normalize::{ccc, is_nfc, nfc, nfd};
pub use numeral::{NumeralError, Radix, is_numeral};
pub use repertoire::{
    Violation, check as repertoire_check, in_repertoire, is_clean as repertoire_clean,
};
pub use segment::{Aksharas, aksharas, aksharas_count, is_devanagari, last_akshara_start};
pub use slp1::{Slp1Error, decode_into as slp1_decode_into, encode_into as slp1_encode_into};

/// Look up a codepoint in a generated `(lo, hi, value)` table.
///
/// Tables are sorted and non-overlapping (enforced by `ucdgen`), so this is a
/// binary search. Returns `default` for codepoints not covered.
#[must_use]
pub fn lookup<T: Copy>(table: &[(u32, u32, T)], cp: u32, default: T) -> T {
    match table.binary_search_by(|&(lo, hi, _)| {
        if cp < lo {
            core::cmp::Ordering::Greater
        } else if cp > hi {
            core::cmp::Ordering::Less
        } else {
            core::cmp::Ordering::Equal
        }
    }) {
        Ok(i) => table[i].2,
        Err(_) => default,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tables::*;

    #[test]
    fn tables_are_sorted_and_disjoint() {
        macro_rules! check {
            ($t:expr, $name:literal) => {
                for w in $t.windows(2) {
                    assert!(w[0].1 < w[1].0, "{} not sorted/disjoint at {:?}", $name, w);
                }
                for e in $t {
                    assert!(e.0 <= e.1, "{} has inverted range {:?}", $name, e);
                }
            };
        }
        check!(GRAPHEME_BREAK, "GRAPHEME_BREAK");
        check!(INCB, "INCB");
        check!(EXTENDED_PICTOGRAPHIC, "EXTENDED_PICTOGRAPHIC");
        check!(XID_START, "XID_START");
        check!(XID_CONTINUE, "XID_CONTINUE");
        check!(DEVANAGARI, "DEVANAGARI");
    }

    #[test]
    fn devanagari_block_is_devanagari() {
        // क U+0915, virama U+094D, digit ० U+0966
        for cp in [0x0915, 0x094D, 0x0966] {
            assert_eq!(lookup(DEVANAGARI, cp, Flag::No), Flag::Yes, "U+{cp:04X}");
        }
        assert_eq!(lookup(DEVANAGARI, 0x0041, Flag::No), Flag::No, "Latin A");
    }

    #[test]
    fn virama_is_an_incb_linker() {
        // This is the property that makes क्ष a single akṣara (doc 01 D-01-A).
        assert_eq!(lookup(INCB, 0x094D, Incb::None), Incb::Linker);
        assert_eq!(lookup(INCB, 0x0915, Incb::None), Incb::Consonant);
    }

    #[test]
    fn identifier_properties() {
        assert_eq!(lookup(XID_START, 0x0915, Flag::No), Flag::Yes, "क starts");
        // Virama is a nonspacing mark: continue, never start. Conjuncts depend on it.
        assert_eq!(lookup(XID_START, 0x094D, Flag::No), Flag::No);
        assert_eq!(lookup(XID_CONTINUE, 0x094D, Flag::No), Flag::Yes);
        // Devanagari digits continue but do not start (doc 01 §2.6).
        assert_eq!(lookup(XID_CONTINUE, 0x0966, Flag::No), Flag::Yes);
        assert_eq!(lookup(XID_START, 0x0966, Flag::No), Flag::No);
    }

    #[test]
    fn grapheme_break_classes() {
        assert_eq!(
            lookup(GRAPHEME_BREAK, 0x094D, GraphemeBreak::Other),
            GraphemeBreak::Extend
        );
        assert_eq!(
            lookup(GRAPHEME_BREAK, 0x200D, GraphemeBreak::Other),
            GraphemeBreak::Zwj
        );
        assert_eq!(
            lookup(GRAPHEME_BREAK, 0x000A, GraphemeBreak::Other),
            GraphemeBreak::Lf
        );
        // I-matra U+093F is a spacing mark — stored after, drawn before.
        assert_eq!(
            lookup(GRAPHEME_BREAK, 0x093F, GraphemeBreak::Other),
            GraphemeBreak::SpacingMark
        );
    }
}
