//! The parse oracle — task `B-034a`, doc 02 §2.2.
//!
//! `B-034` is a tree-sitter grammar for T0. It was attempted in cycle 128 and
//! **deleted rather than shipped**, because the grammar it produced reported
//! zero ERROR nodes while returning entirely wrong trees: twenty-three
//! instructions were swallowed into one `directive` and nothing complained.
//! Absence of errors is not correctness — a parser that accepts everything as
//! one node also reports no errors.
//!
//! So the grammar needs something to be checked AGAINST, and this is it: for
//! every program in the tree, what a correct parse is, one row per statement,
//! produced by the assembler that already has to be right about it. BUILD.md
//! §11's standing rule is *oracle before implementation*, and this applies it
//! to a parser rather than to an instruction encoding.
//!
//! # What it does not cover
//!
//! Comments. The lexer strips from `॰` to end of line before the parser is
//! reached (`B-067`), so a comment is not a statement `sadhana` can see, and a
//! grammar checked against this must account for them separately. Saying so is
//! part of the oracle: an unstated gap is how cycle 128's check passed.
//!
//! The oracle earned that warning on its first use. `spec/bare-metal.sas` has
//! nineteen instructions and twenty-one lines ending in `।` — because Devanagari
//! prose ends a sentence with the same mark Sassembly ends a statement with, and
//! two of its comment lines are prose. `B-011b` hit this from the other side,
//! where a check blamed the DWARF line table for a daṇḍa it found in a comment.
//!
//! So a grammar that terminates a statement on `।` without consuming comments
//! first over-counts by exactly the number of prose sentences in the file, and
//! this is the corpus that says so.
//!
//! Update with `UPDATE_GOLDEN=1 cargo test` and read the diff. A row that moves
//! means a program changed shape, which is exactly the thing worth reviewing.
//!
//! # Why this is split into shards
//!
//! It was one `#[test]` assembling every program in the tree, and it cost 109
//! seconds at 0.99 cores on an idle sixteen-core machine — 23.6% of the whole
//! gate, with fifteen cores idle beside it (`W-078`). The work is real; running
//! it on one core is not. The shards below are the same programs, all of them,
//! divided across threads that were already sitting there.
//!
//! **Sharding a golden test is how a suite goes green by checking less**, so the
//! division is asserted rather than assumed. `every_program_lands_in_exactly_one_shard`
//! proves the shards partition the corpus, and
//! `the_oracle_and_the_tree_name_the_same_programs` proves the corpus has not
//! drifted from the oracle — the hole sharding opens, which the whole-file test
//! did not have. Before the split, a `.sas` file deleted from disk showed up as
//! removed rows in a whole-document comparison; afterwards a file in no shard is
//! a file nobody checks, and only that second assertion catches it.
//!
//! Expect roughly 6-7x and not 12x: `spec/stress-ram.sas` alone is 384 of about
//! 2,800 statements, so **no per-program division can go below the cost of the
//! largest single program.** A reader who raises `SHARDS` and sees no
//! improvement has met that floor, not a defect.

use std::path::{Path, PathBuf};

use sadhana::parse::assemble_program;

fn alloc_line(sign: char, line: &str) -> String {
    format!("  {sign} {line}")
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crates/sadhana has a grandparent")
        .to_path_buf()
}

/// Every `.sas` file in the tree, in a fixed order.
///
/// Sorted, because directory order is a property of the filesystem and doc 03
/// §6 says no generated output may depend on one.
fn programs() -> Vec<PathBuf> {
    static ALL: std::sync::OnceLock<Vec<PathBuf>> = std::sync::OnceLock::new();
    ALL.get_or_init(walk_programs).clone()
}

fn walk_programs() -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut dirs = vec![root().join("spec")];
    while let Some(dir) = dirs.pop() {
        for entry in std::fs::read_dir(&dir).expect("read spec/") {
            let path = entry.expect("entry").path();
            if path.is_dir() {
                dirs.push(path);
            } else if path.extension().is_some_and(|e| e == "sas") {
                out.push(path);
            }
        }
    }
    out.sort();
    assert!(out.len() >= 39, "only {} programs found", out.len());
    out
}

fn shape() -> String {
    let root = root();
    let mut out = String::from(
        "# What a correct parse of every program in the tree is — task `B-034a`.\n\
         #\n\
         # GENERATED by `UPDATE_GOLDEN=1 cargo test -p sadhana --test parse_shape`.\n\
         # Produced by `sadhana`'s own parser, which the conformance corpus and\n\
         # five end-to-end checks already hold to being right about these files.\n\
         #\n\
         # This exists so `B-034b`'s tree-sitter grammar can be checked by\n\
         # COUNTING rather than by absence of ERROR nodes. Cycle 128 shipped a\n\
         # grammar that reported no errors and put twenty-three instructions\n\
         # inside one directive; a parser that accepts everything as one node\n\
         # reports no errors either.\n\
         #\n\
         # Comments are absent: the lexer strips them before the parser runs\n\
         # (`B-067`), so a grammar must account for them separately.\n\
         #\n\
         # Columns: file, line, kind, name\n\
         file\tline\tkind\tname\n",
    );
    for path in programs() {
        let name = path
            .strip_prefix(&root)
            .expect("under the root")
            .to_string_lossy()
            .replace('\\', "/");
        let source = std::fs::read_to_string(&path).expect("read");
        let program = assemble_program(&source).unwrap_or_else(|e| panic!("{name}: {e:?}"));
        for s in &program.statements {
            out.push_str(&format!(
                "{name}\t{}\t{}\t{}\n",
                s.line,
                s.kind.as_str(),
                s.name
            ));
        }
    }
    out
}

/// How many ways the corpus is divided. One `#[test]` each, all in this one
/// binary — so this costs threads, not processes. Splitting into more test
/// FILES would mean more executables, and an exec is far more expensive than a
/// thread.
const SHARDS: usize = 12;

/// The programs belonging to one shard, by stride.
///
/// Stride rather than contiguous blocks: the corpus is sorted by path, adjacent
/// programs are related and similarly sized, and blocks would put every
/// `spec/stress*.sas` in one shard. Interleaving spreads the large ones.
fn shard_paths(shard: usize) -> Vec<PathBuf> {
    programs()
        .into_iter()
        .enumerate()
        .filter(|(i, _)| i % SHARDS == shard)
        .map(|(_, p)| p)
        .collect()
}

/// The repo-relative name the oracle records for a program.
fn oracle_name(path: &Path, root: &Path) -> String {
    path.strip_prefix(root)
        .expect("under the root")
        .to_string_lossy()
        .replace('\\', "/")
}

/// `file\tline\tkind\tname` for each statement in `paths`, in oracle order.
fn rows_for(paths: &[PathBuf]) -> Vec<String> {
    let root = root();
    let mut out = Vec::new();
    for path in paths {
        let name = oracle_name(path, &root);
        let source = std::fs::read_to_string(path).expect("read");
        let program = assemble_program(&source).unwrap_or_else(|e| panic!("{name}: {e:?}"));
        for st in &program.statements {
            out.push(format!(
                "{name}\t{}\t{}\t{}",
                st.line,
                st.kind.as_str(),
                st.name
            ));
        }
    }
    out
}

/// The oracle's data rows, with comments and the column header removed.
///
/// Read once for the whole binary. The shards are threads in one process, so a
/// naive implementation re-reads and re-parses the oracle once per shard.
///
/// This comment used to say that cost **24 seconds** of extra CPU, and said it
/// was measured. It was not, and it is wrong by roughly a thousandfold: `W-089`
/// timed `load_oracle_rows` directly at a **median of 1.72 ms** over 200
/// interleaved runs, unoptimised to match this binary's profile. Eleven avoided
/// re-reads, plus `walk_programs` at 0.791 ms, save about **30 ms** — 0.024% of
/// a 139-second suite, not 17% of it. Keep the `OnceLock`: 30 ms for two lines
/// is worth having, and it also stops twelve threads racing on one file. But
/// keep it for that reason, and not for the one that used to be written here.
///
/// The number survived because it was labelled *measured*. Three suite-level
/// figures for this effect — 2.7 s, 8.6 s and this 24 s — disagreed with each
/// other ninefold and all three were wrong by two orders of magnitude; one
/// minute of direct timing settled it. Before measuring an effect through a
/// system, measure the effect.
fn oracle_rows() -> &'static Vec<String> {
    static ROWS: std::sync::OnceLock<Vec<String>> = std::sync::OnceLock::new();
    ROWS.get_or_init(load_oracle_rows)
}

fn load_oracle_rows() -> Vec<String> {
    let path = root().join("spec/parse-shape-t0.tsv");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("spec/parse-shape-t0.tsv is missing ({e}); UPDATE_GOLDEN=1 writes it")
    });
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty() && !l.starts_with("file\t"))
        .map(str::to_owned)
        .collect()
}

fn file_of(row: &str) -> &str {
    row.split('\t').next().unwrap_or("")
}

/// One shard's programs, checked against the oracle's rows for those programs.
fn check_shard(shard: usize) {
    // `UPDATE_GOLDEN` belongs to `the_oracle_is_rewritten_on_request`, which
    // writes the whole file. The shards return here rather than read a file a
    // sibling test is rewriting on another thread — the one race sharding
    // introduces, closed by not racing.
    if std::env::var_os("UPDATE_GOLDEN").is_some_and(|v| v != "0") {
        return;
    }

    let root = root();
    let paths = shard_paths(shard);
    let mine = rows_for(&paths);
    let files: std::collections::HashSet<String> =
        paths.iter().map(|p| oracle_name(p, &root)).collect();
    let theirs: Vec<String> = oracle_rows()
        .iter()
        .filter(|r| files.contains(file_of(r)))
        .cloned()
        .collect();

    if mine != theirs {
        // Only the rows that moved, as before: a diff nobody can read is not
        // the review this test claims to be.
        let mut moved: Vec<String> = theirs
            .iter()
            .filter(|l| !mine.contains(l))
            .map(|l| alloc_line('-', l))
            .collect();
        moved.extend(
            mine.iter()
                .filter(|l| !theirs.contains(l))
                .map(|l| alloc_line('+', l)),
        );
        panic!(
            "shard {shard}: the parse shape moved in {} row(s); UPDATE_GOLDEN=1 rewrites it:\n{}",
            moved.len(),
            moved.join("\n")
        );
    }
}

macro_rules! shard_tests {
    ($($name:ident => $n:expr),* $(,)?) => {
        $(#[test] fn $name() { check_shard($n); })*
    };
}

shard_tests! {
    parse_shape_shard_00 => 0,
    parse_shape_shard_01 => 1,
    parse_shape_shard_02 => 2,
    parse_shape_shard_03 => 3,
    parse_shape_shard_04 => 4,
    parse_shape_shard_05 => 5,
    parse_shape_shard_06 => 6,
    parse_shape_shard_07 => 7,
    parse_shape_shard_08 => 8,
    parse_shape_shard_09 => 9,
    parse_shape_shard_10 => 10,
    parse_shape_shard_11 => 11,
}

/// The shards partition the corpus: every program in exactly one, none twice.
///
/// Asserted in code because a boundary that drops a program is invisible — the
/// suite gets faster and greener and quietly stops checking something. Cheap:
/// it divides paths and counts them, and assembles nothing.
#[test]
fn every_program_lands_in_exactly_one_shard() {
    let all = programs();
    let mut covered: Vec<PathBuf> = (0..SHARDS).flat_map(shard_paths).collect();
    covered.sort();

    assert_eq!(
        covered.len(),
        all.len(),
        "{} programs across the shards, {} in the tree",
        covered.len(),
        all.len()
    );
    assert_eq!(covered, all, "the shards are not the corpus");

    let mut deduped = covered.clone();
    deduped.dedup();
    assert_eq!(deduped.len(), covered.len(), "a program is in two shards");
}

/// The oracle and the tree name the same programs.
///
/// This is the assertion the whole-file comparison made for free and the shards
/// cannot. Before the split, deleting a `.sas` file showed up as removed rows
/// when the entire generated document was compared against the entire oracle.
/// Now a shard only ever looks at rows for the programs it holds, so a file
/// that vanishes from disk lands in no shard, is checked by nobody, and its
/// rows sit in the oracle unexamined.
#[test]
fn the_oracle_and_the_tree_name_the_same_programs() {
    // Same reason as `check_shard`: while `UPDATE_GOLDEN` is set, the oracle is
    // being rewritten by a sibling test on another thread. Reading it here
    // would race the writer, and `oracle_rows` caches whichever read won — so
    // the whole binary would inherit one thread's timing. There is also nothing
    // to check: the file is about to be regenerated from this very tree.
    if std::env::var_os("UPDATE_GOLDEN").is_some_and(|v| v != "0") {
        return;
    }

    let root = root();
    let on_disk: std::collections::BTreeSet<String> =
        programs().iter().map(|p| oracle_name(p, &root)).collect();
    let in_oracle: std::collections::BTreeSet<String> = oracle_rows()
        .iter()
        .map(|r| file_of(r).to_owned())
        .collect();

    let missing: Vec<&String> = in_oracle.difference(&on_disk).collect();
    let extra: Vec<&String> = on_disk.difference(&in_oracle).collect();
    assert!(
        missing.is_empty(),
        "the oracle has rows for {} program(s) not in the tree — no shard checks \
         these and nothing else would notice: {missing:?}",
        missing.len()
    );
    assert!(
        extra.is_empty(),
        "{} program(s) in the tree have no rows in the oracle; UPDATE_GOLDEN=1 \
         adds them: {extra:?}",
        extra.len()
    );
}

/// Rewrite the oracle when asked. The only writer, so the shards never race it.
#[test]
fn the_oracle_is_rewritten_on_request() {
    if std::env::var_os("UPDATE_GOLDEN").is_none_or(|v| v == "0") {
        return;
    }
    std::fs::write(root().join("spec/parse-shape-t0.tsv"), shape()).expect("write the oracle");
}

#[test]
fn the_oracle_sees_the_directives_that_store_nothing() {
    // Three directives mean nothing storable — `कोष्ठकम्` changes a section,
    // `वैश्विकम्` pushes a name, `स्थानीयम्` does nothing at all — so before
    // `B-034a` the shape of a file was not recoverable from its parse, and a
    // grammar could drop all three unseen.
    let table = std::fs::read_to_string(root().join("spec/parse-shape-t0.tsv")).expect("read");
    for directive in ["कोष्ठकम्", "वैश्विकम्"] {
        assert!(
            table
                .lines()
                .any(|l| l.contains("\tdirective\t") && l.ends_with(directive)),
            "no `{directive}` statement in the oracle"
        );
    }
}

#[test]
fn a_swallowed_statement_changes_the_count() {
    // The failure cycle 128 shipped, stated as a property: if a parser folds a
    // run of statements into one node, the count falls. `namaste.sas` is the
    // program that exercises every kind, and this is the number a grammar must
    // reproduce.
    let table = std::fs::read_to_string(root().join("spec/parse-shape-t0.tsv")).expect("read");
    let rows = |file: &str, kind: &str| {
        table
            .lines()
            .filter(|l| l.starts_with(&format!("{file}\t")) && l.contains(&format!("\t{kind}\t")))
            .count()
    };
    let f = "spec/namaste.sas";
    assert!(rows(f, "instruction") > 10, "{}", rows(f, "instruction"));
    assert!(rows(f, "label") >= 2);
    assert!(rows(f, "directive") >= 2);

    // And every row of every file names a statement kind the parser defines: a
    // fourth word appearing means the oracle and the enum have drifted.
    for line in table.lines().filter(|l| !l.starts_with('#')) {
        let Some(kind) = line.split('\t').nth(2) else {
            continue;
        };
        assert!(
            matches!(kind, "instruction" | "label" | "directive" | "kind"),
            "unknown statement kind `{kind}`"
        );
    }
}
